# Generated by Django 3.2.4 on 2021-08-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getinfor',
            name='output',
        ),
    ]
