# Generated by Django 3.2.4 on 2021-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_remove_getinfor_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='getinfor',
            old_name='pathFile',
            new_name='namefile',
        ),
        migrations.AddField(
            model_name='getinfor',
            name='pathfile',
            field=models.TextField(null=True),
        ),
    ]
