# Generated by Django 3.2.4 on 2021-08-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_auto_20210817_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfor',
            name='namefile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
