# Generated by Django 3.2.4 on 2021-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_auto_20210820_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfor',
            name='Res',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='getinfor',
            name='pathfile',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
