# Generated by Django 3.2.4 on 2021-08-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='edited_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
