# Generated by Django 3.2.4 on 2021-07-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sellerForm',
            new_name='sellerLog',
        ),
    ]
