# Generated by Django 3.2.4 on 2021-07-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_rename_sellerform_sellerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('product', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='sellerLog',
        ),
    ]
